<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="3" ignored="0" total="3" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="43590" started-at="2017-12-29T17:58:24Z" finished-at="2017-12-29T17:59:08Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="43590" started-at="2017-12-29T17:58:24Z" finished-at="2017-12-29T17:59:08Z">
      <class name="com.namtg.tests.Patients">
        <test-method status="PASS" signature="login_Page()[pri:0, instance:com.namtg.tests.Patients@3ffc5af1]" name="login_Page" is-config="true" duration-ms="14272" started-at="2017-12-29T12:58:24Z" finished-at="2017-12-29T12:58:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login_Page -->
        <test-method status="FAIL" signature="Add_prescription()[pri:1, instance:com.namtg.tests.Patients@3ffc5af1]" name="Add_prescription" duration-ms="9" started-at="2017-12-29T12:58:38Z" description="This TC to verify the Add Prescription" finished-at="2017-12-29T12:58:38Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770)
	at org.openqa.selenium.support.ui.FluentWait.<init>(FluentWait.java:96)
	at org.openqa.selenium.support.ui.WebDriverWait.<init>(WebDriverWait.java:71)
	at org.openqa.selenium.support.ui.WebDriverWait.<init>(WebDriverWait.java:45)
	at com.namtg.pages.add_Prescription.clickAddPrescriptionTab(add_Prescription.java:27)
	at com.namtg.tests.Patients.Add_prescription(Patients.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:669)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:877)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1201)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:776)
	at org.testng.TestRunner.run(TestRunner.java:634)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:425)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:420)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:385)
	at org.testng.SuiteRunner.run(SuiteRunner.java:334)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1318)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1243)
	at org.testng.TestNG.runSuites(TestNG.java:1161)
	at org.testng.TestNG.run(TestNG.java:1129)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Add_prescription -->
        <test-method status="PASS" signature="Quite()[pri:0, instance:com.namtg.tests.Patients@3ffc5af1]" name="Quite" is-config="true" duration-ms="755" started-at="2017-12-29T12:58:38Z" finished-at="2017-12-29T12:58:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Quite -->
        <test-method status="PASS" signature="login_Page()[pri:0, instance:com.namtg.tests.Patients@3ffc5af1]" name="login_Page" is-config="true" duration-ms="13691" started-at="2017-12-29T12:58:39Z" finished-at="2017-12-29T12:58:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login_Page -->
        <test-method status="FAIL" signature="Creats_fee()[pri:2, instance:com.namtg.tests.Patients@3ffc5af1]" name="Creats_fee" duration-ms="2" started-at="2017-12-29T12:58:53Z" description="This TC to verify the create fee tab" finished-at="2017-12-29T12:58:53Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.namtg.pages.create_Fee.clickOnTheCreateFeeTab(create_Fee.java:25)
	at com.namtg.tests.Patients.Creats_fee(Patients.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:669)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:877)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1201)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:776)
	at org.testng.TestRunner.run(TestRunner.java:634)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:425)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:420)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:385)
	at org.testng.SuiteRunner.run(SuiteRunner.java:334)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1318)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1243)
	at org.testng.TestNG.runSuites(TestNG.java:1161)
	at org.testng.TestNG.run(TestNG.java:1129)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Creats_fee -->
        <test-method status="PASS" signature="Quite()[pri:0, instance:com.namtg.tests.Patients@3ffc5af1]" name="Quite" is-config="true" duration-ms="613" started-at="2017-12-29T12:58:53Z" finished-at="2017-12-29T12:58:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Quite -->
        <test-method status="PASS" signature="login_Page()[pri:0, instance:com.namtg.tests.Patients@3ffc5af1]" name="login_Page" is-config="true" duration-ms="13505" started-at="2017-12-29T12:58:54Z" finished-at="2017-12-29T12:59:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login_Page -->
        <test-method status="FAIL" signature="report()[pri:3, instance:com.namtg.tests.Patients@3ffc5af1]" name="report" duration-ms="4" started-at="2017-12-29T12:59:07Z" description="This TC to verify the report tab" finished-at="2017-12-29T12:59:07Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.namtg.pages.reports.clickOnTheReportsTab(reports.java:21)
	at com.namtg.tests.Patients.report(Patients.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:669)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:877)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1201)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:776)
	at org.testng.TestRunner.run(TestRunner.java:634)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:425)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:420)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:385)
	at org.testng.SuiteRunner.run(SuiteRunner.java:334)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1318)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1243)
	at org.testng.TestNG.runSuites(TestNG.java:1161)
	at org.testng.TestNG.run(TestNG.java:1129)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- report -->
        <test-method status="PASS" signature="Quite()[pri:0, instance:com.namtg.tests.Patients@3ffc5af1]" name="Quite" is-config="true" duration-ms="717" started-at="2017-12-29T12:59:07Z" finished-at="2017-12-29T12:59:08Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Quite -->
      </class> <!-- com.namtg.tests.Patients -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
